# Generated by Django 6.0.3 on 2026-03-17 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
