# Generated by Django 6.0.3 on 2026-03-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customservice_date_galleryitem_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
